project_id: arun-genai-bb
region: us-central1
bucket: vai-semantic-cache
credentials_json: ./credentials/key.json
text_gen_model_name: gemini-1.0-pro
text_embed_model_name: textembedding-gecko@latest
docai_processor_name: projects/390991481152/locations/us/processors/e554014f261f0011